# Generated by Django 2.0.4 on 2018-04-12 23:38

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'participant',
                'verbose_name_plural': 'participants',
            },
        ),
        migrations.CreateModel(
            name='RegionalAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(choices=[['11', 'ACEH'], ['12', 'SUMATERA UTARA'], ['13', 'SUMATERA BARAT'], ['14', 'RIAU'], ['15', 'JAMBI'], ['16', 'SUMATERA SELATAN'], ['17', 'BENGKULU'], ['18', 'LAMPUNG'], ['19', 'KEPULAUAN BANGKA BELITUNG'], ['21', 'KEPULAUAN RIAU'], ['31', 'DKI JAKARTA'], ['32', 'JAWA BARAT'], ['33', 'JAWA TENGAH'], ['34', 'DI YOGYAKARTA'], ['35', 'JAWA TIMUR'], ['36', 'BANTEN'], ['51', 'BALI'], ['52', 'NUSA TENGGARA BARAT'], ['53', 'NUSA TENGGARA TIMUR'], ['61', 'KALIMANTAN BARAT'], ['62', 'KALIMANTAN TENGAH'], ['63', 'KALIMANTAN SELATAN'], ['64', 'KALIMANTAN TIMUR'], ['65', 'KALIMANTAN UTARA'], ['71', 'SULAWESI UTARA'], ['72', 'SULAWESI TENGAH'], ['73', 'SULAWESI SELATAN'], ['74', 'SULAWESI TENGGARA'], ['75', 'GORONTALO'], ['76', 'SULAWESI BARAT'], ['81', 'MALUKU'], ['82', 'MALUKU UTARA'], ['91', 'PAPUA BARAT'], ['94', 'PAPUA']], max_length=2, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'admin region',
                'verbose_name_plural': 'admin region',
            },
        ),
    ]
