# Generated by Django 2.0.4 on 2018-04-17 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='regionaladmin',
            options={'verbose_name': 'regional admin', 'verbose_name_plural': 'regional admins'},
        ),
    ]
