# Generated by Django 2.0.4 on 2018-04-17 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20180417_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regionaladmin',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Province'),
        ),
    ]
