# Generated by Django 2.0.4 on 2018-05-03 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('region', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diklat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateTimeField()),
                ('location', models.CharField(max_length=200)),
                ('duration', models.PositiveSmallIntegerField()),
                ('supervisor', models.CharField(max_length=200)),
                ('respondents', models.PositiveSmallIntegerField()),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='region.Province')),
                ('regency', models.ManyToManyField(to='region.Regency')),
            ],
            options={
                'verbose_name': 'diklat',
                'verbose_name_plural': 'diklat',
            },
        ),
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'measure',
                'verbose_name_plural': 'measures',
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('order', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name': 'option',
                'verbose_name_plural': 'options',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('0', 'essay'), ('1', 'objective'), ('2', 'group of objective')], max_length=1)),
                ('text', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'question',
                'verbose_name_plural': 'questions',
            },
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument', models.CharField(choices=[('0', 'Instrument A'), ('1', 'Instrument B'), ('2', 'Instrument C')], max_length=2)),
                ('diklat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Diklat')),
            ],
            options={
                'verbose_name': 'questionnaire',
                'verbose_name_plural': 'questionnaires',
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, default='')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Question')),
                ('respondent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Respondent')),
            ],
            options={
                'verbose_name': 'recommendation',
                'verbose_name_plural': 'recommendations',
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('measure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Measure')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Question')),
                ('respondent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Respondent')),
                ('selected', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Option')),
            ],
            options={
                'verbose_name': 'response',
                'verbose_name_plural': 'responses',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Topic')),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Questionnaire')),
            ],
            options={
                'verbose_name': 'topic',
                'verbose_name_plural': 'topics',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Topic'),
        ),
        migrations.AddField(
            model_name='option',
            name='question',
            field=models.ForeignKey(limit_choices_to={'type__in': ['1', '2']}, on_delete=django.db.models.deletion.CASCADE, to='main.Question'),
        ),
        migrations.AddField(
            model_name='measure',
            name='question',
            field=models.ForeignKey(limit_choices_to={'type__in': ['2', '3']}, on_delete=django.db.models.deletion.CASCADE, to='main.Question'),
        ),
        migrations.AlterUniqueTogether(
            name='questionnaire',
            unique_together={('diklat', 'instrument')},
        ),
    ]
