# Generated by Django 2.0.5 on 2018-05-07 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('region', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diklat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateTimeField()),
                ('location', models.CharField(max_length=200)),
                ('duration', models.PositiveSmallIntegerField()),
                ('supervisor', models.CharField(max_length=200)),
                ('num_of_participant', models.PositiveSmallIntegerField()),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='region.Province')),
                ('regencies', models.ManyToManyField(to='region.Regency')),
            ],
            options={
                'verbose_name': 'diklat',
                'verbose_name_plural': 'diklat',
            },
        ),
        migrations.CreateModel(
            name='EssayResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'essay response',
                'verbose_name_plural': 'essay responses',
            },
        ),
        migrations.CreateModel(
            name='GroupOfObjectiveResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'group of objective response',
                'verbose_name_plural': 'group of objective responses',
            },
        ),
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'measure',
                'verbose_name_plural': 'measures',
            },
        ),
        migrations.CreateModel(
            name='ObjectiveResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'objective response',
                'verbose_name_plural': 'objective responses',
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=5)),
            ],
            options={
                'verbose_name': 'option',
                'verbose_name_plural': 'options',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('essay', 'Essay'), ('objective', 'Objective'), ('group_of_objective', 'Group of objective')], max_length=18)),
                ('text', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'question',
                'verbose_name_plural': 'questions',
            },
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('instrument', models.CharField(choices=[('instrument_a', 'Instrument A'), ('instrument_b', 'Instrument B'), ('instrument_c', 'Instrument C'), ('instrument_d', 'Instrument D'), ('instrument_e', 'Instrument E')], max_length=12)),
                ('diklat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Diklat')),
            ],
            options={
                'verbose_name': 'questionnaire',
                'verbose_name_plural': 'questionnaires',
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, default='')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Question')),
                ('respondent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Respondent')),
            ],
            options={
                'verbose_name': 'recommendation',
                'verbose_name_plural': 'recommendations',
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('essay', 'Essay'), ('objective', 'Objective'), ('group_of_objective', 'Group of objective')], max_length=18)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Question')),
                ('respondent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Respondent')),
            ],
            options={
                'verbose_name': 'response',
                'verbose_name_plural': 'responses',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Topic')),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Questionnaire')),
            ],
            options={
                'verbose_name': 'topic',
                'verbose_name_plural': 'topics',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Topic'),
        ),
        migrations.AddField(
            model_name='option',
            name='question',
            field=models.ForeignKey(limit_choices_to={'type__in': ['objective', 'group_of_objective']}, on_delete=django.db.models.deletion.CASCADE, to='main.Question'),
        ),
        migrations.AddField(
            model_name='objectiveresponse',
            name='response',
            field=models.OneToOneField(limit_choices_to={'type': 'objective'}, on_delete=django.db.models.deletion.CASCADE, to='main.Response'),
        ),
        migrations.AddField(
            model_name='objectiveresponse',
            name='selected',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Option'),
        ),
        migrations.AddField(
            model_name='measure',
            name='question',
            field=models.ForeignKey(limit_choices_to={'type__in': ['objective', 'group_of_objective']}, on_delete=django.db.models.deletion.CASCADE, to='main.Question'),
        ),
        migrations.AddField(
            model_name='groupofobjectiveresponse',
            name='measure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Measure'),
        ),
        migrations.AddField(
            model_name='groupofobjectiveresponse',
            name='response',
            field=models.OneToOneField(limit_choices_to={'type': 'group_of_objective'}, on_delete=django.db.models.deletion.CASCADE, to='main.Response'),
        ),
        migrations.AddField(
            model_name='groupofobjectiveresponse',
            name='selected',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Option'),
        ),
        migrations.AddField(
            model_name='essayresponse',
            name='response',
            field=models.OneToOneField(limit_choices_to={'type': 'essay'}, on_delete=django.db.models.deletion.CASCADE, to='main.Response'),
        ),
        migrations.AlterUniqueTogether(
            name='recommendation',
            unique_together={('respondent', 'question')},
        ),
        migrations.AlterUniqueTogether(
            name='questionnaire',
            unique_together={('diklat', 'instrument')},
        ),
    ]
