# Generated by Django 2.0.4 on 2018-05-03 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diklat',
            old_name='respondents',
            new_name='num_of_participant',
        ),
        migrations.RenameField(
            model_name='diklat',
            old_name='regency',
            new_name='regencies',
        ),
    ]
