# Generated by Django 2.0.4 on 2018-04-24 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180424_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
