# Generated by Django 2.0.4 on 2018-04-17 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180417_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diklat',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
