# Generated by Django 2.0.4 on 2018-05-03 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180503_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='title',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
