# Generated by Django 2.0.4 on 2018-04-24 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_recommendation_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
