# Generated by Django 2.0.4 on 2018-04-17 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20180417_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diklat',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Province'),
        ),
        migrations.RemoveField(
            model_name='diklat',
            name='regency',
        ),
        migrations.AddField(
            model_name='diklat',
            name='regency',
            field=models.ManyToManyField(to='main.Regency'),
        ),
    ]
