# Generated by Django 2.0.4 on 2018-04-20 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='province',
            options={'verbose_name': 'province', 'verbose_name_plural': 'provincies'},
        ),
        migrations.AlterModelOptions(
            name='regency',
            options={'verbose_name': 'regency', 'verbose_name_plural': 'regencies'},
        ),
    ]
