# Generated by Django 2.0.4 on 2018-04-24 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0002_auto_20180420_2214'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='province',
            options={'verbose_name': 'province', 'verbose_name_plural': 'provinces'},
        ),
    ]
